// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fx-protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using ProtoBuf = global::Google.Protobuf;
using ProtoBufCollections = global::Google.Protobuf.Collections;
using ProtoBufReflection = global::Google.Protobuf.Reflection;
namespace seesv.protocol;

/// <summary>Holder for reflection information generated from fx-protocol.proto</summary>
public static partial class FxProtocolReflection {

#region Descriptor
/// <summary>File descriptor for fx-protocol.proto</summary>
public static ProtoBufReflection::FileDescriptor Descriptor {
  get { return descriptor; }
}
private static ProtoBufReflection::FileDescriptor descriptor;

static FxProtocolReflection() {
  byte[] descriptorData = global::System.Convert.FromBase64String(
      string.Concat(
        "ChFmeC1wcm90b2NvbC5wcm90byJOCgtMUG9pbnRBdWRpbxIMCgRnYWluGAEg",
        "ASgBEg8KB2xwb2ludDAYAiADKAISDwoHbHBvaW50MRgDIAMoAhIPCgdscG9p",
        "bnQyGAQgAygCIh8KDExldmVsVHJpZ2dlchIPCgdkZWNpYmVsGAEgASgBIiMK",
        "B1dzQXVkaW8SDAoEZ2FpbhgBIAEoARIKCgJ3cxgCIAMoAiKfAQoLQmVhbWZv",
        "cm1pbmcSDAoEZ2FpbhgBIAEoARIKCgJiZhgCIAMoARINCgVsZXZlbBgDIAMo",
        "ARIOCgZwYXJhbTEYBCADKAUSDgoGcGFyYW0yGAUgAygFEg0KBXRoZXRhGAYg",
        "AygFEgwKBHBvc1gYByADKAUSDAoEcG9zWRgIIAMoBRINCgV2UG9zWBgJIAMo",
        "BRINCgV2UG9zWRgKIAMoBSKdAgoFRXZlbnQSCgoCaWQYASABKAUSHgoEdHlw",
        "ZRgCIAEoDjIQLkV2ZW50LkV2ZW50VHlwZRIeCgZscG9pbnQYAyABKAsyDC5M",
        "UG9pbnRBdWRpb0gAEhYKAndzGAQgASgLMgguV3NBdWRpb0gAEiMKC2JlYW1m",
        "b3JtaW5nGAUgASgLMgwuQmVhbWZvcm1pbmdIABIeCgVsZXZlbBgGIAEoCzIN",
        "LkxldmVsVHJpZ2dlckgAEhEKCXRpbWVzdGFtcBgHIAEoCSJQCglFdmVudFR5",
        "cGUSDwoLQkVBTUZPUk1JTkcQABIRCg1MRVZFTF9UUklHR0VSEAESDAoIV1Nf",
        "QVVESU8QAhIRCg1MX1BPSU5UX0FVRElPEANCBgoEZGF0YSJwCglTdWJzY3Jp",
        "YmUSJgoEdHlwZRgBIAEoDjIYLlN1YnNjcmliZS5TdWJzY3JpYmVUeXBlEgoK",
        "AmlkGAIgASgFIi8KDVN1YnNjcmliZVR5cGUSDQoJU1VCU0NSSUJFEAASDwoL",
        "VU5TVUJTQ1JJQkUQAUIRqgIOc2Vlc3YucHJvdG9jb2xiBnByb3RvMw=="));
  descriptor = ProtoBufReflection::FileDescriptor.FromGeneratedCode(descriptorData,
      new ProtoBufReflection::FileDescriptor[] { },
      new ProtoBufReflection::GeneratedClrTypeInfo(null, null, new ProtoBufReflection::GeneratedClrTypeInfo[] {
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.LPointAudio), global::seesv.protocol.LPointAudio.Parser, new[]{ "Gain", "Lpoint0", "Lpoint1", "Lpoint2" }, null, null, null, null),
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.LevelTrigger), global::seesv.protocol.LevelTrigger.Parser, new[]{ "Decibel" }, null, null, null, null),
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.WsAudio), global::seesv.protocol.WsAudio.Parser, new[]{ "Gain", "Ws" }, null, null, null, null),
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.Beamforming), global::seesv.protocol.Beamforming.Parser, new[]{ "Gain", "Bf", "Level", "Param1", "Param2", "Theta", "PosX", "PosY", "VPosX", "VPosY" }, null, null, null, null),
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.Event), global::seesv.protocol.Event.Parser, new[]{ "Id", "Type", "Lpoint", "Ws", "Beamforming", "Level", "Timestamp" }, new[]{ "Data" }, new[]{ typeof(global::seesv.protocol.Event.Types.EventType) }, null, null),
        new ProtoBufReflection::GeneratedClrTypeInfo(typeof(global::seesv.protocol.Subscribe), global::seesv.protocol.Subscribe.Parser, new[]{ "Type", "Id" }, null, new[]{ typeof(global::seesv.protocol.Subscribe.Types.SubscribeType) }, null, null)
      }));
}
#endregion

}
#region Messages
public sealed partial class LPointAudio : ProtoBuf::IMessage<LPointAudio> {
private static readonly ProtoBuf::MessageParser<LPointAudio> _parser = new ProtoBuf::MessageParser<LPointAudio>(() => new LPointAudio());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<LPointAudio> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[0]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LPointAudio() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LPointAudio(LPointAudio other) : this() {
  gain_ = other.gain_;
  lpoint0_ = other.lpoint0_.Clone();
  lpoint1_ = other.lpoint1_.Clone();
  lpoint2_ = other.lpoint2_.Clone();
  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LPointAudio Clone() {
  return new LPointAudio(this);
}

/// <summary>Field number for the "gain" field.</summary>
public const int GainFieldNumber = 1;
private double gain_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public double Gain {
  get { return gain_; }
  set {
    gain_ = value;
  }
}

/// <summary>Field number for the "lpoint0" field.</summary>
public const int Lpoint0FieldNumber = 2;
private static readonly ProtoBuf::FieldCodec<float> _repeated_lpoint0_codec
    = ProtoBuf::FieldCodec.ForFloat(18);
private readonly ProtoBufCollections::RepeatedField<float> lpoint0_ = new ProtoBufCollections::RepeatedField<float>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<float> Lpoint0 {
  get { return lpoint0_; }
}

/// <summary>Field number for the "lpoint1" field.</summary>
public const int Lpoint1FieldNumber = 3;
private static readonly ProtoBuf::FieldCodec<float> _repeated_lpoint1_codec
    = ProtoBuf::FieldCodec.ForFloat(26);
private readonly ProtoBufCollections::RepeatedField<float> lpoint1_ = new ProtoBufCollections::RepeatedField<float>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<float> Lpoint1 {
  get { return lpoint1_; }
}

/// <summary>Field number for the "lpoint2" field.</summary>
public const int Lpoint2FieldNumber = 4;
private static readonly ProtoBuf::FieldCodec<float> _repeated_lpoint2_codec
    = ProtoBuf::FieldCodec.ForFloat(34);
private readonly ProtoBufCollections::RepeatedField<float> lpoint2_ = new ProtoBufCollections::RepeatedField<float>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<float> Lpoint2 {
  get { return lpoint2_; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as LPointAudio);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(LPointAudio other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (!ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Gain, other.Gain)) return false;
  if(!lpoint0_.Equals(other.lpoint0_)) return false;
  if(!lpoint1_.Equals(other.lpoint1_)) return false;
  if(!lpoint2_.Equals(other.lpoint2_)) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Gain != 0D) hash ^= ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Gain);
  hash ^= lpoint0_.GetHashCode();
  hash ^= lpoint1_.GetHashCode();
  hash ^= lpoint2_.GetHashCode();
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Gain != 0D) {
    output.WriteRawTag(9);
    output.WriteDouble(Gain);
  }
  lpoint0_.WriteTo(output, _repeated_lpoint0_codec);
  lpoint1_.WriteTo(output, _repeated_lpoint1_codec);
  lpoint2_.WriteTo(output, _repeated_lpoint2_codec);
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Gain != 0D) {
    size += 1 + 8;
  }
  size += lpoint0_.CalculateSize(_repeated_lpoint0_codec);
  size += lpoint1_.CalculateSize(_repeated_lpoint1_codec);
  size += lpoint2_.CalculateSize(_repeated_lpoint2_codec);
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(LPointAudio other) {
  if (other == null) {
    return;
  }
  if (other.Gain != 0D) {
    Gain = other.Gain;
  }
  lpoint0_.Add(other.lpoint0_);
  lpoint1_.Add(other.lpoint1_);
  lpoint2_.Add(other.lpoint2_);
  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 9: {
        Gain = input.ReadDouble();
        break;
      }
      case 18:
      case 21: {
        lpoint0_.AddEntriesFrom(input, _repeated_lpoint0_codec);
        break;
      }
      case 26:
      case 29: {
        lpoint1_.AddEntriesFrom(input, _repeated_lpoint1_codec);
        break;
      }
      case 34:
      case 37: {
        lpoint2_.AddEntriesFrom(input, _repeated_lpoint2_codec);
        break;
      }
    }
  }
}

}

public sealed partial class LevelTrigger : ProtoBuf::IMessage<LevelTrigger> {
private static readonly ProtoBuf::MessageParser<LevelTrigger> _parser = new ProtoBuf::MessageParser<LevelTrigger>(() => new LevelTrigger());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<LevelTrigger> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[1]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LevelTrigger() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LevelTrigger(LevelTrigger other) : this() {
  decibel_ = other.decibel_;
  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public LevelTrigger Clone() {
  return new LevelTrigger(this);
}

/// <summary>Field number for the "decibel" field.</summary>
public const int DecibelFieldNumber = 1;
private double decibel_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public double Decibel {
  get { return decibel_; }
  set {
    decibel_ = value;
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as LevelTrigger);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(LevelTrigger other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (!ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Decibel, other.Decibel)) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Decibel != 0D) hash ^= ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Decibel);
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Decibel != 0D) {
    output.WriteRawTag(9);
    output.WriteDouble(Decibel);
  }
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Decibel != 0D) {
    size += 1 + 8;
  }
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(LevelTrigger other) {
  if (other == null) {
    return;
  }
  if (other.Decibel != 0D) {
    Decibel = other.Decibel;
  }
  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 9: {
        Decibel = input.ReadDouble();
        break;
      }
    }
  }
}

}

public sealed partial class WsAudio : ProtoBuf::IMessage<WsAudio> {
private static readonly ProtoBuf::MessageParser<WsAudio> _parser = new ProtoBuf::MessageParser<WsAudio>(() => new WsAudio());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<WsAudio> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[2]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public WsAudio() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public WsAudio(WsAudio other) : this() {
  gain_ = other.gain_;
  ws_ = other.ws_.Clone();
  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public WsAudio Clone() {
  return new WsAudio(this);
}

/// <summary>Field number for the "gain" field.</summary>
public const int GainFieldNumber = 1;
private double gain_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public double Gain {
  get { return gain_; }
  set {
    gain_ = value;
  }
}

/// <summary>Field number for the "ws" field.</summary>
public const int WsFieldNumber = 2;
private static readonly ProtoBuf::FieldCodec<float> _repeated_ws_codec
    = ProtoBuf::FieldCodec.ForFloat(18);
private readonly ProtoBufCollections::RepeatedField<float> ws_ = new ProtoBufCollections::RepeatedField<float>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<float> Ws {
  get { return ws_; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as WsAudio);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(WsAudio other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (!ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Gain, other.Gain)) return false;
  if(!ws_.Equals(other.ws_)) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Gain != 0D) hash ^= ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Gain);
  hash ^= ws_.GetHashCode();
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Gain != 0D) {
    output.WriteRawTag(9);
    output.WriteDouble(Gain);
  }
  ws_.WriteTo(output, _repeated_ws_codec);
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Gain != 0D) {
    size += 1 + 8;
  }
  size += ws_.CalculateSize(_repeated_ws_codec);
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(WsAudio other) {
  if (other == null) {
    return;
  }
  if (other.Gain != 0D) {
    Gain = other.Gain;
  }
  ws_.Add(other.ws_);
  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 9: {
        Gain = input.ReadDouble();
        break;
      }
      case 18:
      case 21: {
        ws_.AddEntriesFrom(input, _repeated_ws_codec);
        break;
      }
    }
  }
}

}

public sealed partial class Beamforming : ProtoBuf::IMessage<Beamforming> {
private static readonly ProtoBuf::MessageParser<Beamforming> _parser = new ProtoBuf::MessageParser<Beamforming>(() => new Beamforming());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<Beamforming> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[3]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Beamforming() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Beamforming(Beamforming other) : this() {
  gain_ = other.gain_;
  bf_ = other.bf_.Clone();
  level_ = other.level_.Clone();
  param1_ = other.param1_.Clone();
  param2_ = other.param2_.Clone();
  theta_ = other.theta_.Clone();
  posX_ = other.posX_.Clone();
  posY_ = other.posY_.Clone();
  vPosX_ = other.vPosX_.Clone();
  vPosY_ = other.vPosY_.Clone();
  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Beamforming Clone() {
  return new Beamforming(this);
}

/// <summary>Field number for the "gain" field.</summary>
public const int GainFieldNumber = 1;
private double gain_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public double Gain {
  get { return gain_; }
  set {
    gain_ = value;
  }
}

/// <summary>Field number for the "bf" field.</summary>
public const int BfFieldNumber = 2;
private static readonly ProtoBuf::FieldCodec<double> _repeated_bf_codec
    = ProtoBuf::FieldCodec.ForDouble(18);
private readonly ProtoBufCollections::RepeatedField<double> bf_ = new ProtoBufCollections::RepeatedField<double>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<double> Bf {
  get { return bf_; }
}

/// <summary>Field number for the "level" field.</summary>
public const int LevelFieldNumber = 3;
private static readonly ProtoBuf::FieldCodec<double> _repeated_level_codec
    = ProtoBuf::FieldCodec.ForDouble(26);
private readonly ProtoBufCollections::RepeatedField<double> level_ = new ProtoBufCollections::RepeatedField<double>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<double> Level {
  get { return level_; }
}

/// <summary>Field number for the "param1" field.</summary>
public const int Param1FieldNumber = 4;
private static readonly ProtoBuf::FieldCodec<int> _repeated_param1_codec
    = ProtoBuf::FieldCodec.ForInt32(34);
private readonly ProtoBufCollections::RepeatedField<int> param1_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> Param1 {
  get { return param1_; }
}

/// <summary>Field number for the "param2" field.</summary>
public const int Param2FieldNumber = 5;
private static readonly ProtoBuf::FieldCodec<int> _repeated_param2_codec
    = ProtoBuf::FieldCodec.ForInt32(42);
private readonly ProtoBufCollections::RepeatedField<int> param2_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> Param2 {
  get { return param2_; }
}

/// <summary>Field number for the "theta" field.</summary>
public const int ThetaFieldNumber = 6;
private static readonly ProtoBuf::FieldCodec<int> _repeated_theta_codec
    = ProtoBuf::FieldCodec.ForInt32(50);
private readonly ProtoBufCollections::RepeatedField<int> theta_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> Theta {
  get { return theta_; }
}

/// <summary>Field number for the "posX" field.</summary>
public const int PosXFieldNumber = 7;
private static readonly ProtoBuf::FieldCodec<int> _repeated_posX_codec
    = ProtoBuf::FieldCodec.ForInt32(58);
private readonly ProtoBufCollections::RepeatedField<int> posX_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> PosX {
  get { return posX_; }
}

/// <summary>Field number for the "posY" field.</summary>
public const int PosYFieldNumber = 8;
private static readonly ProtoBuf::FieldCodec<int> _repeated_posY_codec
    = ProtoBuf::FieldCodec.ForInt32(66);
private readonly ProtoBufCollections::RepeatedField<int> posY_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> PosY {
  get { return posY_; }
}

/// <summary>Field number for the "vPosX" field.</summary>
public const int VPosXFieldNumber = 9;
private static readonly ProtoBuf::FieldCodec<int> _repeated_vPosX_codec
    = ProtoBuf::FieldCodec.ForInt32(74);
private readonly ProtoBufCollections::RepeatedField<int> vPosX_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> VPosX {
  get { return vPosX_; }
}

/// <summary>Field number for the "vPosY" field.</summary>
public const int VPosYFieldNumber = 10;
private static readonly ProtoBuf::FieldCodec<int> _repeated_vPosY_codec
    = ProtoBuf::FieldCodec.ForInt32(82);
private readonly ProtoBufCollections::RepeatedField<int> vPosY_ = new ProtoBufCollections::RepeatedField<int>();
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public ProtoBufCollections::RepeatedField<int> VPosY {
  get { return vPosY_; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as Beamforming);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(Beamforming other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (!ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Gain, other.Gain)) return false;
  if(!bf_.Equals(other.bf_)) return false;
  if(!level_.Equals(other.level_)) return false;
  if(!param1_.Equals(other.param1_)) return false;
  if(!param2_.Equals(other.param2_)) return false;
  if(!theta_.Equals(other.theta_)) return false;
  if(!posX_.Equals(other.posX_)) return false;
  if(!posY_.Equals(other.posY_)) return false;
  if(!vPosX_.Equals(other.vPosX_)) return false;
  if(!vPosY_.Equals(other.vPosY_)) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Gain != 0D) hash ^= ProtoBufCollections::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Gain);
  hash ^= bf_.GetHashCode();
  hash ^= level_.GetHashCode();
  hash ^= param1_.GetHashCode();
  hash ^= param2_.GetHashCode();
  hash ^= theta_.GetHashCode();
  hash ^= posX_.GetHashCode();
  hash ^= posY_.GetHashCode();
  hash ^= vPosX_.GetHashCode();
  hash ^= vPosY_.GetHashCode();
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Gain != 0D) {
    output.WriteRawTag(9);
    output.WriteDouble(Gain);
  }
  bf_.WriteTo(output, _repeated_bf_codec);
  level_.WriteTo(output, _repeated_level_codec);
  param1_.WriteTo(output, _repeated_param1_codec);
  param2_.WriteTo(output, _repeated_param2_codec);
  theta_.WriteTo(output, _repeated_theta_codec);
  posX_.WriteTo(output, _repeated_posX_codec);
  posY_.WriteTo(output, _repeated_posY_codec);
  vPosX_.WriteTo(output, _repeated_vPosX_codec);
  vPosY_.WriteTo(output, _repeated_vPosY_codec);
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Gain != 0D) {
    size += 1 + 8;
  }
  size += bf_.CalculateSize(_repeated_bf_codec);
  size += level_.CalculateSize(_repeated_level_codec);
  size += param1_.CalculateSize(_repeated_param1_codec);
  size += param2_.CalculateSize(_repeated_param2_codec);
  size += theta_.CalculateSize(_repeated_theta_codec);
  size += posX_.CalculateSize(_repeated_posX_codec);
  size += posY_.CalculateSize(_repeated_posY_codec);
  size += vPosX_.CalculateSize(_repeated_vPosX_codec);
  size += vPosY_.CalculateSize(_repeated_vPosY_codec);
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(Beamforming other) {
  if (other == null) {
    return;
  }
  if (other.Gain != 0D) {
    Gain = other.Gain;
  }
  bf_.Add(other.bf_);
  level_.Add(other.level_);
  param1_.Add(other.param1_);
  param2_.Add(other.param2_);
  theta_.Add(other.theta_);
  posX_.Add(other.posX_);
  posY_.Add(other.posY_);
  vPosX_.Add(other.vPosX_);
  vPosY_.Add(other.vPosY_);
  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 9: {
        Gain = input.ReadDouble();
        break;
      }
      case 18:
      case 17: {
        bf_.AddEntriesFrom(input, _repeated_bf_codec);
        break;
      }
      case 26:
      case 25: {
        level_.AddEntriesFrom(input, _repeated_level_codec);
        break;
      }
      case 34:
      case 32: {
        param1_.AddEntriesFrom(input, _repeated_param1_codec);
        break;
      }
      case 42:
      case 40: {
        param2_.AddEntriesFrom(input, _repeated_param2_codec);
        break;
      }
      case 50:
      case 48: {
        theta_.AddEntriesFrom(input, _repeated_theta_codec);
        break;
      }
      case 58:
      case 56: {
        posX_.AddEntriesFrom(input, _repeated_posX_codec);
        break;
      }
      case 66:
      case 64: {
        posY_.AddEntriesFrom(input, _repeated_posY_codec);
        break;
      }
      case 74:
      case 72: {
        vPosX_.AddEntriesFrom(input, _repeated_vPosX_codec);
        break;
      }
      case 82:
      case 80: {
        vPosY_.AddEntriesFrom(input, _repeated_vPosY_codec);
        break;
      }
    }
  }
}

}

public sealed partial class Event : ProtoBuf::IMessage<Event> {
private static readonly ProtoBuf::MessageParser<Event> _parser = new ProtoBuf::MessageParser<Event>(() => new Event());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<Event> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[4]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Event() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Event(Event other) : this() {
  id_ = other.id_;
  type_ = other.type_;
  timestamp_ = other.timestamp_;
  switch (other.DataCase) {
    case DataOneofCase.Lpoint:
      Lpoint = other.Lpoint.Clone();
      break;
    case DataOneofCase.Ws:
      Ws = other.Ws.Clone();
      break;
    case DataOneofCase.Beamforming:
      Beamforming = other.Beamforming.Clone();
      break;
    case DataOneofCase.Level:
      Level = other.Level.Clone();
      break;
  }

  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Event Clone() {
  return new Event(this);
}

/// <summary>Field number for the "id" field.</summary>
public const int IdFieldNumber = 1;
private int id_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int Id {
  get { return id_; }
  set {
    id_ = value;
  }
}

/// <summary>Field number for the "type" field.</summary>
public const int TypeFieldNumber = 2;
private global::seesv.protocol.Event.Types.EventType type_ = global::seesv.protocol.Event.Types.EventType.Beamforming;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.Event.Types.EventType Type {
  get { return type_; }
  set {
    type_ = value;
  }
}

/// <summary>Field number for the "lpoint" field.</summary>
public const int LpointFieldNumber = 3;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.LPointAudio Lpoint {
  get { return dataCase_ == DataOneofCase.Lpoint ? (global::seesv.protocol.LPointAudio) data_ : null; }
  set {
    data_ = value;
    dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Lpoint;
  }
}

/// <summary>Field number for the "ws" field.</summary>
public const int WsFieldNumber = 4;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.WsAudio Ws {
  get { return dataCase_ == DataOneofCase.Ws ? (global::seesv.protocol.WsAudio) data_ : null; }
  set {
    data_ = value;
    dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Ws;
  }
}

/// <summary>Field number for the "beamforming" field.</summary>
public const int BeamformingFieldNumber = 5;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.Beamforming Beamforming {
  get { return dataCase_ == DataOneofCase.Beamforming ? (global::seesv.protocol.Beamforming) data_ : null; }
  set {
    data_ = value;
    dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Beamforming;
  }
}

/// <summary>Field number for the "level" field.</summary>
public const int LevelFieldNumber = 6;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.LevelTrigger Level {
  get { return dataCase_ == DataOneofCase.Level ? (global::seesv.protocol.LevelTrigger) data_ : null; }
  set {
    data_ = value;
    dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Level;
  }
}

/// <summary>Field number for the "timestamp" field.</summary>
public const int TimestampFieldNumber = 7;
private string timestamp_ = "";
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public string Timestamp {
  get { return timestamp_; }
  set {
    timestamp_ = ProtoBuf::ProtoPreconditions.CheckNotNull(value, "value");
  }
}

private object data_;
/// <summary>Enum of possible cases for the "data" oneof.</summary>
public enum DataOneofCase {
  None = 0,
  Lpoint = 3,
  Ws = 4,
  Beamforming = 5,
  Level = 6,
}
private DataOneofCase dataCase_ = DataOneofCase.None;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public DataOneofCase DataCase {
  get { return dataCase_; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void ClearData() {
  dataCase_ = DataOneofCase.None;
  data_ = null;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as Event);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(Event other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (Id != other.Id) return false;
  if (Type != other.Type) return false;
  if (!object.Equals(Lpoint, other.Lpoint)) return false;
  if (!object.Equals(Ws, other.Ws)) return false;
  if (!object.Equals(Beamforming, other.Beamforming)) return false;
  if (!object.Equals(Level, other.Level)) return false;
  if (Timestamp != other.Timestamp) return false;
  if (DataCase != other.DataCase) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Id != 0) hash ^= Id.GetHashCode();
  if (Type != global::seesv.protocol.Event.Types.EventType.Beamforming) hash ^= Type.GetHashCode();
  if (dataCase_ == DataOneofCase.Lpoint) hash ^= Lpoint.GetHashCode();
  if (dataCase_ == DataOneofCase.Ws) hash ^= Ws.GetHashCode();
  if (dataCase_ == DataOneofCase.Beamforming) hash ^= Beamforming.GetHashCode();
  if (dataCase_ == DataOneofCase.Level) hash ^= Level.GetHashCode();
  if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
  hash ^= (int) dataCase_;
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Id != 0) {
    output.WriteRawTag(8);
    output.WriteInt32(Id);
  }
  if (Type != global::seesv.protocol.Event.Types.EventType.Beamforming) {
    output.WriteRawTag(16);
    output.WriteEnum((int) Type);
  }
  if (dataCase_ == DataOneofCase.Lpoint) {
    output.WriteRawTag(26);
    output.WriteMessage(Lpoint);
  }
  if (dataCase_ == DataOneofCase.Ws) {
    output.WriteRawTag(34);
    output.WriteMessage(Ws);
  }
  if (dataCase_ == DataOneofCase.Beamforming) {
    output.WriteRawTag(42);
    output.WriteMessage(Beamforming);
  }
  if (dataCase_ == DataOneofCase.Level) {
    output.WriteRawTag(50);
    output.WriteMessage(Level);
  }
  if (Timestamp.Length != 0) {
    output.WriteRawTag(58);
    output.WriteString(Timestamp);
  }
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Id != 0) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeInt32Size(Id);
  }
  if (Type != global::seesv.protocol.Event.Types.EventType.Beamforming) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeEnumSize((int) Type);
  }
  if (dataCase_ == DataOneofCase.Lpoint) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeMessageSize(Lpoint);
  }
  if (dataCase_ == DataOneofCase.Ws) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeMessageSize(Ws);
  }
  if (dataCase_ == DataOneofCase.Beamforming) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeMessageSize(Beamforming);
  }
  if (dataCase_ == DataOneofCase.Level) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeMessageSize(Level);
  }
  if (Timestamp.Length != 0) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeStringSize(Timestamp);
  }
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(Event other) {
  if (other == null) {
    return;
  }
  if (other.Id != 0) {
    Id = other.Id;
  }
  if (other.Type != global::seesv.protocol.Event.Types.EventType.Beamforming) {
    Type = other.Type;
  }
  if (other.Timestamp.Length != 0) {
    Timestamp = other.Timestamp;
  }
  switch (other.DataCase) {
    case DataOneofCase.Lpoint:
      if (Lpoint == null) {
        Lpoint = new global::seesv.protocol.LPointAudio();
      }
      Lpoint.MergeFrom(other.Lpoint);
      break;
    case DataOneofCase.Ws:
      if (Ws == null) {
        Ws = new global::seesv.protocol.WsAudio();
      }
      Ws.MergeFrom(other.Ws);
      break;
    case DataOneofCase.Beamforming:
      if (Beamforming == null) {
        Beamforming = new global::seesv.protocol.Beamforming();
      }
      Beamforming.MergeFrom(other.Beamforming);
      break;
    case DataOneofCase.Level:
      if (Level == null) {
        Level = new global::seesv.protocol.LevelTrigger();
      }
      Level.MergeFrom(other.Level);
      break;
  }

  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 8: {
        Id = input.ReadInt32();
        break;
      }
      case 16: {
        Type = (global::seesv.protocol.Event.Types.EventType) input.ReadEnum();
        break;
      }
      case 26: {
        global::seesv.protocol.LPointAudio subBuilder = new global::seesv.protocol.LPointAudio();
        if (dataCase_ == DataOneofCase.Lpoint) {
          subBuilder.MergeFrom(Lpoint);
        }
        input.ReadMessage(subBuilder);
        Lpoint = subBuilder;
        break;
      }
      case 34: {
        global::seesv.protocol.WsAudio subBuilder = new global::seesv.protocol.WsAudio();
        if (dataCase_ == DataOneofCase.Ws) {
          subBuilder.MergeFrom(Ws);
        }
        input.ReadMessage(subBuilder);
        Ws = subBuilder;
        break;
      }
      case 42: {
        global::seesv.protocol.Beamforming subBuilder = new global::seesv.protocol.Beamforming();
        if (dataCase_ == DataOneofCase.Beamforming) {
          subBuilder.MergeFrom(Beamforming);
        }
        input.ReadMessage(subBuilder);
        Beamforming = subBuilder;
        break;
      }
      case 50: {
        global::seesv.protocol.LevelTrigger subBuilder = new global::seesv.protocol.LevelTrigger();
        if (dataCase_ == DataOneofCase.Level) {
          subBuilder.MergeFrom(Level);
        }
        input.ReadMessage(subBuilder);
        Level = subBuilder;
        break;
      }
      case 58: {
        Timestamp = input.ReadString();
        break;
      }
    }
  }
}

#region Nested types
/// <summary>Container for nested types declared in the Event message type.</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static partial class Types {
  public enum EventType {
    [ProtoBufReflection::OriginalName("BEAMFORMING")] Beamforming = 0,
    [ProtoBufReflection::OriginalName("LEVEL_TRIGGER")] LevelTrigger = 1,
    [ProtoBufReflection::OriginalName("WS_AUDIO")] WsAudio = 2,
    [ProtoBufReflection::OriginalName("L_POINT_AUDIO")] LPointAudio = 3,
  }

}
#endregion

}

public sealed partial class Subscribe : ProtoBuf::IMessage<Subscribe> {
private static readonly ProtoBuf::MessageParser<Subscribe> _parser = new ProtoBuf::MessageParser<Subscribe>(() => new Subscribe());
private ProtoBuf::UnknownFieldSet _unknownFields;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBuf::MessageParser<Subscribe> Parser { get { return _parser; } }

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static ProtoBufReflection::MessageDescriptor Descriptor {
  get { return global::seesv.protocol.FxProtocolReflection.Descriptor.MessageTypes[5]; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
ProtoBufReflection::MessageDescriptor ProtoBuf::IMessage.Descriptor {
  get { return Descriptor; }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Subscribe() {
  OnConstruction();
}

partial void OnConstruction();

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Subscribe(Subscribe other) : this() {
  type_ = other.type_;
  id_ = other.id_;
  _unknownFields = ProtoBuf::UnknownFieldSet.Clone(other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public Subscribe Clone() {
  return new Subscribe(this);
}

/// <summary>Field number for the "type" field.</summary>
public const int TypeFieldNumber = 1;
private global::seesv.protocol.Subscribe.Types.SubscribeType type_ = global::seesv.protocol.Subscribe.Types.SubscribeType.Subscribe;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public global::seesv.protocol.Subscribe.Types.SubscribeType Type {
  get { return type_; }
  set {
    type_ = value;
  }
}

/// <summary>Field number for the "id" field.</summary>
public const int IdFieldNumber = 2;
private int id_;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int Id {
  get { return id_; }
  set {
    id_ = value;
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override bool Equals(object other) {
  return Equals(other as Subscribe);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public bool Equals(Subscribe other) {
  if (ReferenceEquals(other, null)) {
    return false;
  }
  if (ReferenceEquals(other, this)) {
    return true;
  }
  if (Type != other.Type) return false;
  if (Id != other.Id) return false;
  return Equals(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override int GetHashCode() {
  int hash = 1;
  if (Type != global::seesv.protocol.Subscribe.Types.SubscribeType.Subscribe) hash ^= Type.GetHashCode();
  if (Id != 0) hash ^= Id.GetHashCode();
  if (_unknownFields != null) {
    hash ^= _unknownFields.GetHashCode();
  }
  return hash;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public override string ToString() {
  return ProtoBuf::JsonFormatter.ToDiagnosticString(this);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void WriteTo(ProtoBuf::CodedOutputStream output) {
  if (Type != global::seesv.protocol.Subscribe.Types.SubscribeType.Subscribe) {
    output.WriteRawTag(8);
    output.WriteEnum((int) Type);
  }
  if (Id != 0) {
    output.WriteRawTag(16);
    output.WriteInt32(Id);
  }
  if (_unknownFields != null) {
    _unknownFields.WriteTo(output);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public int CalculateSize() {
  int size = 0;
  if (Type != global::seesv.protocol.Subscribe.Types.SubscribeType.Subscribe) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeEnumSize((int) Type);
  }
  if (Id != 0) {
    size += 1 + ProtoBuf::CodedOutputStream.ComputeInt32Size(Id);
  }
  if (_unknownFields != null) {
    size += _unknownFields.CalculateSize();
  }
  return size;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(Subscribe other) {
  if (other == null) {
    return;
  }
  if (other.Type != global::seesv.protocol.Subscribe.Types.SubscribeType.Subscribe) {
    Type = other.Type;
  }
  if (other.Id != 0) {
    Id = other.Id;
  }
  _unknownFields = ProtoBuf::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public void MergeFrom(ProtoBuf::CodedInputStream input) {
  uint tag;
  while ((tag = input.ReadTag()) != 0) {
    switch(tag) {
      default:
        _unknownFields = ProtoBuf::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
        break;
      case 8: {
        Type = (global::seesv.protocol.Subscribe.Types.SubscribeType) input.ReadEnum();
        break;
      }
      case 16: {
        Id = input.ReadInt32();
        break;
      }
    }
  }
}

#region Nested types
/// <summary>Container for nested types declared in the Subscribe message type.</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
public static partial class Types {
  public enum SubscribeType {
    [ProtoBufReflection::OriginalName("SUBSCRIBE")] Subscribe = 0,
    [ProtoBufReflection::OriginalName("UNSUBSCRIBE")] Unsubscribe = 1,
  }

}
#endregion

}

#endregion

#endregion Designer generated code